services:
  - type: web
    name: cyphercraft-api
    env: python
    runtime: python-3.11.9
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FASTAPI_ENV
        value: production
    autoDeploy: true